add support for lnot on ints and uints
flux-rs/flux pull request #574
Opened 2023-12-07 23:14 UTC by enjhnsn2

fixes #571

2023-12-08 00:43 UTC, nilehmann requested changes
@enjhnsn2 looks good, but some errors need to be fixed.

We also need to add the signatures [here](https://github.com/flux-rs/flux/blob/main/crates/flux-refineck/src/sigs/overflow.rs/#L30). We have a different set of signatures depending on whether overflow checking is enabled. Overflow is not relevant for `!` but we still need to duplicate the signature.

Also, can you add a test [here](https://github.com/flux-rs/flux/blob/main/crates/flux-tests/tests/pos/surface/binop.rs#L81)?

2023-12-08 00:43 UTC, nilehmann commented on crates/flux-refineck/src/sigs/default.rs
> +        (mir::UnOp::Not, s!(fn(a: Int) -> Int[E::tt()]))
This needs to be

```suggestion
        (mir::UnOp::Not, s!(fn(a: Int) -> Int{ v: E::tt() }))
```


`Int[E::tt()]` would mean the integer is indexed by a `bool` which is not well-formed.

2023-12-08 18:06 UTC, enjhnsn2 commented
it was my impression (from context) that `E::tt()` told Flux to treat the operorator as an uninterpreted function, as in the other bitwise operations:
```Rust
// BIT
(BitAnd, s!(fn(a: Int, b: Int) -> Int{v: E::tt()})),
(BitOr,  s!(fn(a: Int, b: Int) -> Int{v: E::tt()})),
```

2023-12-13 08:02 UTC, nilehmann approved these changes
Looks good to me. I'm going to mer it.

2023-12-13 08:02 UTC, merged