Check impl-methods are subtypes of trait-methods
flux-rs/flux pull request #864
Opened 2024-10-26 21:49 UTC by ranjitjhala

Fixes #592

2024-10-29 17:37 UTC, ranjitjhala commented
Matching PR https://github.com/PLSysSec/tock/pull/4/files

2024-10-29 19:28 UTC, nilehmann approved these changes
I'm fine with merging this, but we should refactor this out of `Checker` sooner rather than later as it's only going to get more complicated.

2024-10-29 19:28 UTC, nilehmann commented on crates/flux-refineck/src/checker.rs
> +    fn has_trusted_impl(genv: &GlobalEnv, def_id: DefId) -> bool {
nit: I'd make this a method in `GlobalEnv`

2024-10-29 19:28 UTC, nilehmann commented on crates/flux-refineck/src/checker.rs
> +                        infcx.define_vars(&param.sort)
I find this extremely confusing and I think it's wrong in subtle ways. It'd probably help to refactor this outside of `Checker` and use a separate `InferCtxt` (there's no reason to make this part of the constraint generated for the body). Moving this out of `Checker` could also help with improving the error message

2024-10-29 19:38 UTC, nilehmann requested changes
no wait, I think I know what's wrong with this. We are assuming the trait method and the impl method have the same number of refinement generics. This is true for type generics and that's why we can instantiate the impl method with the (rebased) identity instantiation, but requiring the same number of refinement generics won't fly. I believe we should instantiate refinement generics with inference variables.

2024-10-29 19:41 UTC, nilehmann reviewed
No scratch that. I'm super confused

2024-10-29 19:56 UTC, nilehmann approved these changes
Well, I'm still a bit confused, but I think a lot of my confusion would be solved by using a separate `InferCtxt`. I feel that initializing the `InferCtxt` in the context of the trait would automatically do most of this right.

2024-10-30 00:08 UTC, ranjitjhala commented
By "outside" `Checker` do you mean it should be at the "level" of `fn check_fn` in `flux-refineck/src/lib.rs`?

2024-10-30 00:10 UTC, ranjitjhala commented
or at the level of `fn run_in_refine_mode`?

2024-10-30 00:15 UTC, nilehmann commented
I think this should be part of [`flux_fhir_analysis::compare_impl_item::check_impl_against_trait`](https://flux-rs.github.io/flux/doc/flux_fhir_analysis/compare_impl_item/fn.check_impl_against_trait.html), but that would require reshuffling things across crates. Putting it in [`flux_refineck::check_fn`](https://flux-rs.github.io/flux/doc/flux_refineck/fn.check_fn.html) would be a good start though.

2024-10-30 03:41 UTC, ranjitjhala commented
AFAICT `InferCtxt` can only be initialized with a `Body` and so you can't initialize it in the context of a trait-method (which may not have a `Body`?)

2024-10-30 16:28 UTC, ranjitjhala commented
@nilehmann I have done the refactoring, so the impl-trait check lives in

* `pub fn trait_impl_subtyping` (currently in checker.rs) but independent of the `Checker` itself and
* invoked as `PHASE 4` in `check_fn`

See esp. the new `args` passed into `RefineTree::new` and the subsequent `.instantiate(...)`

2024-10-30 17:08 UTC, nilehmann approved these changes

2024-10-30 17:08 UTC, nilehmann commented on crates/flux-middle/src/rty/mod.rs
> +}
I believe we only use `identity_for_item_new` 

```suggestion
    fn identity_for_item(genv: &GlobalEnv, def_id: DefId) -> QueryResult<RefineArgs> {
        let reft_generics = genv.refinement_generics_of(def_id)?;
        let mut args = vec![];
        for i in 0..reft_generics.count() {
            let param = reft_generics.param_at(i, *genv)?;
            let expr =
                Expr::var(Var::EarlyParam(EarlyReftParam { index: i as u32, name: param.name }));
            args.push(expr);
        }
        Ok(List::from_vec(args))
    }
}
```

If we need them both, we should implement one in terms of the other. Or we can have a `for_item` and an `identity_for_item`, both implemented on top of `fill_item` as we do for `GenericArgs`.

2024-10-30 17:08 UTC, nilehmann commented on crates/flux-refineck/src/checker.rs
> +
```suggestion
```

2024-10-30 17:08 UTC, nilehmann commented on crates/flux-infer/src/infer.rs
> +    // }
```suggestion
```

2024-10-30 17:46 UTC, ranjitjhala commented
ok, I'll merge if everything -- IF I get the damn tock thing to pass locally.

2024-10-30 20:14 UTC, merged

2024-10-30 20:14 UTC, ranjitjhala commented
merging!