A bit of function subtyping for `ReifyFnPointer`
flux-rs/flux pull request #874
Opened 2024-11-05 18:46 UTC by ranjitjhala

Fixes #859

2024-11-12 16:38 UTC, nilehmann requested changes
I don't like this, `FnDef` is not technically a subtype of `FnPtr` and we are not gaining anything by making it (since fn ptrs are unrefined). I'd prefer if we do the subtyping when we check the cast (`ReifyFnPointer`). That would allow us to give a better error message. We can revisit if we ever need refined function pointers.

2024-11-12 16:49 UTC, ranjitjhala commented
> I'd prefer if we do the subtyping when we check the cast (ReifyFnPointer).

that would indeed be preferable but I don’t see how that’s possible since at that point we don’t know what the “super-type” is supposed to be?

2024-11-12 16:51 UTC, ranjitjhala commented
At best one can imagine 
1. generating a KVAR template at the cast site and creating a subtyping constraint there and 
2. then generating a subtyping between the template and the actual super type at the actual usage site 

but that seems rather overkill to me and really what the FnDef is avoiding.

2024-11-12 16:54 UTC, ranjitjhala commented
So I’d say what we’re “gaining” is avoiding this redundant indirection through Kvars, unless you see some other way to do it?

2024-11-12 17:13 UTC, nilehmann commented
We do know the type because it's unrefined. When checking a cast we have the rust target type (which in this case should be a `FnPtr`). We need the default refinement for that type and then check against it.

2024-11-12 17:46 UTC, ranjitjhala commented
Ah yes of course, we do _now_ but (hopefully soon) we'll want to refine the `FnPtr` and then we won't have that info, so why paint into a corner?

2024-11-12 18:16 UTC, nilehmann commented
I'm not convinced this is the best way to support refined function pointers. If we want the function pointer to be higher-rank we could instead put some refinement parameters (the ones not mentioned in clauses) as part of `Binder` instead of `EarlyBinder`. Also, storing a function in a variable and then applying it multiple times is rare so I'm not even convinced we need it to be higher-rank, at which point this is just an optimization (to avoid extra kvars).

2024-11-13 21:57 UTC, ranjitjhala commented
Ok @nilehmann have moved the subtyping to the cast site.

2024-11-14 22:26 UTC, nilehmann approved these changes
LGTM, just a couple of nits

2024-11-14 22:26 UTC, nilehmann commented on crates/flux-refineck/src/checker.rs
> +pub fn infer_under_mut_ref_hack(
```suggestion
fn infer_under_mut_ref_hack(
```

2024-11-14 22:26 UTC, nilehmann commented on crates/flux-refineck/src/checker.rs
> +pub fn check_fn_subtyping(
```suggestion
fn check_fn_subtyping(
```

2024-11-15 04:32 UTC, merged